# Site settings

url: "http://smartrunningteam.github.io"
title: "Smart Running Team"
description: "Een enthousiaste groep lopers uit Beveren. Fan van middellange en lange afstanden"
# keywords: ""
favicon: "/img/favicon.jpg"
# black-favicon: "/img/black-lab-glass.ico"
# google-tracking-id: ""
# disqus-shortname: ""

#permalink: pretty ## pretty or 404 page, tough choise ##
excerpt_separator: <!--more-->

# Navigation bar links
# Blog link in the blog and post pages will point to the blog.html#blog
# In the default page it will point to the preview of the last post

pages_list:
  Over ons: 'about'
  Blog: 'blog'
  Atleten: 'atleten'
# Photos: 'photos'
  Contact: 'contact'

bg-0: "/img/bg-0.jpg"
bg-1: "/img/bg-1.jpg"
bg-2: "/img/bg-2.jpg"
bg-3: "/img/bg-3.jpg"

banner: "/img/banner-std.jpg"
banner-blog: "/img/banner-blog.jpg"
banner-athletes : "/img/banner-athletes.jpg"

# flickr:
#   api_key: ?SHOULD THIS BE PUBLIC?

# Blog variables
paginate: 15

paginate_path: "blog/page:num"

post-preview-words: 128

fb-share: True
twitter-share: True
reddit-share: false


# Social networks variables (many more available: facebook, flickr, dribbble, pinterest, instagram, tumblr etc.)
social:
  - title: "rss"
    url: "/feed.xml"
  - title: "github"
    url: "https://github.com/SmartRunningTeam"
  - title: "twitter"
    url: "https://twitter.com/WeRunSmart"
##  - title: "linkedin"
##    url: "http://no.linkedin.com/in/PanosSakkos"
##  - title: "youtube"
##    url: "http://youtube.com/c/PanosSakkos"
##  - title: "soundcloud"
##    url: "https://soundcloud.com/psakkos/"

404-img: "/img/404.png"

# Exclusion list from the generated _site
exclude: ["Rakefile", "LICENSE", "readme.markdown", "vendor"]
