# Site settings

url: "http://smartrunningteam.github.io"
title: "Smart Running Team"
description: "Een enthousiaste groep lopers uit Beveren. Fan van middellange en lange afstanden"
# keywords: ""
favicon: "/img/favicon.png"
# google-tracking-id: ""
# disqus-shortname: ""
force-https: True

#permalink: pretty ## pretty or 404 page, tough choise ##
excerpt_separator: <!--more-->
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

# Dynamic Text on the Header
dynamic-typing: True
shuffle: False # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 2000
lines: # You can add HTML Tags in the Text
  - text: "We."
  - text: "We Run."
  - text: "We Run Wegels."
  - text: "We Run Wegels in Beveren."
  - text: "We Run Fast."
  - text: "We Run Smart."
  - text: "We Run Fast and Smart."
  - text: "We Run our Life."

indextext: Should work

# Navigation bar links
# Blog link in the blog and post pages will point to the blog.html#blog
# In the default page it will point to the preview of the last post

pages_list:
  Over ons: 'about'
# Levensloop: 'levensloop'
  Blog: 'blog'
  Atleten: 'atleten'
# Photos: 'photos'
  Contact: 'contact'

bg-0: "/img/bg-0.jpg"
bg-1: "/img/bg-1.jpg"
bg-2: "/img/bg-2.jpg"
bg-3: "/img/bg-3.jpg"

banner: "/img/banner-std.jpg"
banner-blog: "/img/banner-blog.jpg"


# Blog variables
paginate: 15

paginate_path: "blog/page:num"

post-preview-words: 128

fb-share: True
twitter-share: True
reddit-share: false

email: wimmeul@gmail.com

# Social networks variables (many more available: facebook, flickr, dribbble, pinterest, instagram, tumblr etc.)
social:
  - title: "rss"
    url: "/feed.xml"
  - title: "github"
    url: "https://github.com/SmartRunningTeam"
  - title: "twitter"
    url: "https://twitter.com/WeRunSmart"

# Exclusion list from the generated _site
exclude: ["Rakefile", "LICENSE", "readme.markdown", "vendor"]
